### ISSUE TITLE
Plugin suggests you to download application/x-shockwave-flash

### ISSUE THREAD

**Issue by Zyostes** [gtraxx/tinymce-plugin-youtube#11]
Hi,

My configuration is : 

- tinymce 4.1.0 ;
- in a Symfony2 2.4.2 environment ;
- tested on Mozilla Firefox 29.0.1.

On change in youtube url input (write or paste), the browser suggests you to download an application/x-shockwave-flash (sometime one time, sometime two times).

![tinymce_youtube_bug](https://cloud.githubusercontent.com/assets/5689105/3338642/9c03e426-f85e-11e3-96b1-775028f1ff04.png)

Thank you,
Baptiste.

**Comment by jpatel3** [comment]
+1 same issue.
