### ISSUE TITLE
Problem with button / checkbox 

### ISSUE THREAD

**Issue by Kevkehz** [gtraxx/tinymce-plugin-youtube#13]
Hello, <br>
I have some bug with the layout of the button 'submit' and the last checkbox. <br>
 When i open the youtube plugin, i see this screen shoot, i check my website on chrome 35, safari 7, firefox 30. There's always this layout.

![capture decran 2014-06-29 a 11 34 46](https://cloud.githubusercontent.com/assets/7477133/3422899/1f34cfd6-ff71-11e3-84d3-c8bef8ab3329.png)

**Comment by RicherYang** [comment]
I find in the file /dist/youtube.zip of js/main.js
It don't have code
```javascript
 HTML5: parent.tinymce.util.I18n.translate("html5"),
 Insert: parent.tinymce.util.I18n.translate("Insert")
```
let the layout loss some item
