### ISSUE TITLE
There is no possibility to dismiss the window

### ISSUE THREAD

**Issue by eximius313** [gtraxx/tinymce-plugin-youtube#18]
When I'm opening the window, but then I decide that I don't want to insert video I can not do it.
There is no "cancel" neither "close" button.

**Comment by gtraxx** [comment]
I'll add a button

**Comment by eximius313** [comment]
one quick comment: https://github.com/gtraxx/tinymce-plugin-youtube/commit/9fa7395df0322c48943ba093da8d151d16e820bf#commitcomment-18395537
