### ISSUE TITLE
Video doesn't appear without "iframe" option

### ISSUE THREAD

**Issue by eximius313** [gtraxx/tinymce-plugin-youtube#19]
When one deselects the "iframe" option:
![image](https://cloud.githubusercontent.com/assets/5578017/13581275/6be6455a-e4a6-11e5-93d5-fe1969dd9a90.png)

There is a blank space instead of inerted video

**Comment by gtraxx** [comment]
Hi, Youtube does work with most flash but requires iframes
View new API from You Tube :)

**Comment by eximius313** [comment]
So why option to disable iframe is available if it doesn't work?

**Comment by gtraxx** [comment]
I'll edit the window and options :)
