### ISSUE TITLE
Youtube.min.js in last release

### ISSUE THREAD

**Issue by genyslt** [gtraxx/tinymce-plugin-youtube#27]
![image](https://user-images.githubusercontent.com/12429511/37209520-405e49c0-23ae-11e8-90f4-7ad4cdb04938.png)

Lithuanian translate:

tinymce.addI18n('lt', {
    'YouTube Tooltip'   : "YouTube",
    'YouTube Title'     : "Įterpti YouTube Video",
    'Youtube URL'       : 'Nuoroda',
    'Youtube ID'        : 'http://youtu.be/xxxxxxxx arba http://www.youtube.com/watch?v=xxxxxxxx',
    'width'             : 'Plotis',
    'height'            : 'Aukštis',
    'autoplay'          : 'Autoplay',
    'Related video'     : 'Susijęs video',
    'HD video'          : 'HD kokybė',
    'cancel'            : 'Atšaukti',
    'Insert'            : 'Įterpti'
});

**Comment by gtraxx** [comment]
Hi, I'll check :D
