### ISSUE TITLE
What are you think about tinymce 5?

### ISSUE THREAD

**Issue by Nelo-cool** [gtraxx/tinymce-plugin-youtube#29]
Hello, will you update the plugin or not?

**Comment by gtraxx** [comment]
Hi, I am working on a version compatible with tinyMCE 5 :)

**Comment by Nelo-cool** [comment]
Thanks! I am waiting for you with best regards. Good luck! :)

**Comment by gtraxx** [comment]
We are waiting for information and change in tinymce 5
> That won't work because the use of an url include is not supported anymore by tinymce 5 tinymce/tinymce#4786

**Comment by Nelo-cool** [comment]
Okay, thanks for information!

**Comment by gtraxx** [comment]
Hi, test youtube plugin for tinymce 5 : https://github.com/gtraxx/tinymce-plugin-youtube/tree/tinymce5

**Comment by Nelo-cool** [comment]
Ok! Thanks! I will test on next week! Excuse me for long waiting response.

**Comment by gtraxx** [comment]
:D

**Comment by gtraxx** [comment]
Hi, youtube plugin for tinymce 5 is now in master :)

**Comment by Nelo-cool** [comment]
Thanks man! I will use now it:)
